name: bundle-extension

on:
  push:
    tags:
      - "v[1-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

# I used the following project as template to get started:
# https://github.com/dessant/search-by-image/blob/master/.github/workflows/ci.yml

jobs:
  build:
    permissions:
      contents: write # for creating release
    name: Build packages ðŸ“¦
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Clone repository â¬‡ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Get release information ðŸ› 
        id: release_info
        run: |
          echo "{VERSION}=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Build extensions packages
        run: |
          utils/make-chromium.sh ${{ steps.release_info.outputs.VERSION }}
          utils/make-firefox.sh ${{ steps.release_info.outputs.VERSION }}
      - name: Create release and upload artifact ðŸš€
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.release_info.outputs.VERSION }}"
          prerelease: false
          files: |
            dist/build/*.zip
            dist/build/*.crx
            dist/build/*.xpi
